// !!! This content is generated by the multiplayer backend tool. Do not modify manually !!!
// !!! Last Updated (DD/MM/YYYY HH:MM:SS CET): 28/09/2024 14:22:12 CEST !!!

export enum OriginType {
	Server = "server",
	Owner = "owner",
	Guest = "guest"
};

export type SendPermissions = { [key in OriginType]: boolean };

export type MessageElementDescriptor = {
	byteSize: number,
	offset: number,
	description: string,
	type: string
};

export type EventSpecification = {
	id: number,
	name: string,
	permissions: SendPermissions,
	expectedMinSize: number
	structure: MessageElementDescriptor[]
};

export enum EVENTS {
	DEBUG_INFO = 0,
	PLAYER_JOINED = 1,
	PLAYER_JOIN_ATTEMPT = 2,
	PLAYER_JOIN_ACCEPTED = 3,
	PLAYER_JOIN_DECLINED = 4,
	PLAYER_LEFT = 5,
	LOBBY_CLOSING = 6,
	PLAYER_LEAVING = 7,
	SERVER_CLOSING = 8,
	ENTER_LOCATION = 1001,
	PLAYER_MOVE = 1002,
	DIFFICULTY_SELECT_FOR_MINIGAME = 2000,
	DIFFICULTY_CONFIRMED_FOR_MINIGAME = 2001,
	PLAYERS_DECLARE_INTENT_FOR_MINIGAME = 2002,
	PLAYER_READY_FOR_MINIGAME = 2003,
	PLAYER_ABORTING_MINIGAME = 2004,
	ENTER_MINIGAME = 2005,
};

/** DebugInfo Message Structure
 *
 * *	0b --> 4b:	uint32    :	HTTP Code (if applicable)
 * *	4b --> +Nb:	string    :	Debug message
 */
export const DEBUG_INFO_EVENT: EventSpecification = {
	id: EVENTS.DEBUG_INFO,
	name: "DebugInfo",
	permissions: {guest: true, owner: true, server: true},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "HTTP Code (if applicable)",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Debug message",
			type: "string"
		}
	]
}
/** PlayerJoined Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_JOINED_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_JOINED,
	name: "PlayerJoined",
	permissions: {guest: false, owner: false, server: true},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** PlayerJoinAttempt Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_JOIN_ATTEMPT_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_JOIN_ATTEMPT,
	name: "PlayerJoinAttempt",
	permissions: {guest: false, owner: false, server: true},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** PlayerJoinAccepted Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_JOIN_ACCEPTED_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_JOIN_ACCEPTED,
	name: "PlayerJoinAccepted",
	permissions: {guest: false, owner: true, server: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** PlayerJoinDeclined Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_JOIN_DECLINED_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_JOIN_DECLINED,
	name: "PlayerJoinDeclined",
	permissions: {owner: true, server: false, guest: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** PlayerLeft Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_LEFT_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_LEFT,
	name: "PlayerLeft",
	permissions: {server: true, guest: false, owner: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** LobbyClosing Message Structure
 *
 */
export const LOBBY_CLOSING_EVENT: EventSpecification = {
	id: EVENTS.LOBBY_CLOSING,
	name: "LobbyClosing",
	permissions: {server: true, guest: false, owner: false},
	expectedMinSize: 8,
	structure: [
	]
}
/** PlayerLeaving Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_LEAVING_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_LEAVING,
	name: "PlayerLeaving",
	permissions: {guest: true, owner: true, server: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** ServerClosing Message Structure
 *
 */
export const SERVER_CLOSING_EVENT: EventSpecification = {
	id: EVENTS.SERVER_CLOSING,
	name: "ServerClosing",
	permissions: {guest: false, owner: false, server: true},
	expectedMinSize: 8,
	structure: [
	]
}
/** EnterLocation Message Structure
 *
 * *	0b --> 4b:	uint32    :	Location ID
 */
export const ENTER_LOCATION_EVENT: EventSpecification = {
	id: EVENTS.ENTER_LOCATION,
	name: "EnterLocation",
	permissions: {guest: false, owner: true, server: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Location ID",
			type: "uint32"
		}
	]
}
/** PlayerMove Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> 8b:	uint32    :	Location ID
 */
export const PLAYER_MOVE_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_MOVE,
	name: "PlayerMove",
	permissions: {server: false, guest: true, owner: true},
	expectedMinSize: 16,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 4,
			offset: 4,
			description: "Location ID",
			type: "uint32"
		}
	]
}
/** DifficultySelectForMinigame Message Structure
 *
 * *	0b --> 4b:	uint32    :	Minigame ID
 * *	4b --> 8b:	uint32    :	Difficulty ID
 * *	8b --> +Nb:	string    :	Difficulty Name
 */
export const DIFFICULTY_SELECT_FOR_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.DIFFICULTY_SELECT_FOR_MINIGAME,
	name: "DifficultySelectForMinigame",
	permissions: {server: false, guest: false, owner: true},
	expectedMinSize: 16,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Minigame ID",
			type: "uint32"
		},
		{
			byteSize: 4,
			offset: 4,
			description: "Difficulty ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 8,
			description: "Difficulty Name",
			type: "string"
		}
	]
}
/** DifficultyConfirmedForMinigame Message Structure
 *
 * *	0b --> 4b:	uint32    :	Minigame ID
 * *	4b --> 8b:	uint32    :	Difficulty ID
 * *	8b --> +Nb:	string    :	Difficulty Name
 */
export const DIFFICULTY_CONFIRMED_FOR_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.DIFFICULTY_CONFIRMED_FOR_MINIGAME,
	name: "DifficultyConfirmedForMinigame",
	permissions: {server: false, guest: false, owner: true},
	expectedMinSize: 16,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Minigame ID",
			type: "uint32"
		},
		{
			byteSize: 4,
			offset: 4,
			description: "Difficulty ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 8,
			description: "Difficulty Name",
			type: "string"
		}
	]
}
/** PlayersDeclareIntentForMinigame Message Structure
 *
 */
export const PLAYERS_DECLARE_INTENT_FOR_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.PLAYERS_DECLARE_INTENT_FOR_MINIGAME,
	name: "PlayersDeclareIntentForMinigame",
	permissions: {guest: false, owner: false, server: true},
	expectedMinSize: 8,
	structure: [
	]
}
/** PlayerReadyForMinigame Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_READY_FOR_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_READY_FOR_MINIGAME,
	name: "PlayerReadyForMinigame",
	permissions: {guest: true, owner: true, server: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** PlayerAbortingMinigame Message Structure
 *
 * *	0b --> 4b:	uint32    :	Player ID
 * *	4b --> +Nb:	string    :	Player IGN
 */
export const PLAYER_ABORTING_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.PLAYER_ABORTING_MINIGAME,
	name: "PlayerAbortingMinigame",
	permissions: {guest: true, owner: true, server: false},
	expectedMinSize: 12,
	structure: [
		{
			byteSize: 4,
			offset: 0,
			description: "Player ID",
			type: "uint32"
		},
		{
			byteSize: 0,
			offset: 4,
			description: "Player IGN",
			type: "string"
		}
	]
}
/** EnterMinigame Message Structure
 *
 */
export const ENTER_MINIGAME_EVENT: EventSpecification = {
	id: EVENTS.ENTER_MINIGAME,
	name: "EnterMinigame",
	permissions: {guest: false, owner: false, server: true},
	expectedMinSize: 8,
	structure: [
	]
}

export const EVENT_ID_MAP: {[key: number]: EventSpecification} = {
	0: DEBUG_INFO_EVENT,
	1: PLAYER_JOINED_EVENT,
	2: PLAYER_JOIN_ATTEMPT_EVENT,
	3: PLAYER_JOIN_ACCEPTED_EVENT,
	4: PLAYER_JOIN_DECLINED_EVENT,
	5: PLAYER_LEFT_EVENT,
	6: LOBBY_CLOSING_EVENT,
	7: PLAYER_LEAVING_EVENT,
	8: SERVER_CLOSING_EVENT,
	1001: ENTER_LOCATION_EVENT,
	1002: PLAYER_MOVE_EVENT,
	2000: DIFFICULTY_SELECT_FOR_MINIGAME_EVENT,
	2001: DIFFICULTY_CONFIRMED_FOR_MINIGAME_EVENT,
	2002: PLAYERS_DECLARE_INTENT_FOR_MINIGAME_EVENT,
	2003: PLAYER_READY_FOR_MINIGAME_EVENT,
	2004: PLAYER_ABORTING_MINIGAME_EVENT,
	2005: ENTER_MINIGAME_EVENT
};
